# Generated by Django 3.2.8 on 2021-10-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_digital'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping',
            new_name='ShippingAddress',
        ),
    ]
